fix

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -81,51 +81,51 @@ jobs:
           # Build Docker images and tag them with the version
           VERSION=$(cat ./version/version.txt)
           echo "VERSION: $VERSION"
-          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/users-service:$VERSION ./micro-services/users-service
-          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/movies-service:$VERSION ./micro-services/movies-service
-          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/search-service:$VERSION ./micro-services/search-service
-          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sessions-service:$VERSION ./micro-services/sessions-service
-          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/rooms-service:$VERSION ./micro-services/rooms-service
-          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/notifications-service:$VERSION ./micro-services/notifications-service
-          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/front-app:$VERSION ./front
-          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/prometheus-service:$VERSION ./monitoring/prometheus
+          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/users-service:${VERSION} ./micro-services/users-service
+          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/movies-service:${VERSION} ./micro-services/movies-service
+          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/search-service:${VERSION} ./micro-services/search-service
+          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sessions-service:${VERSION} ./micro-services/sessions-service
+          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/rooms-service:${VERSION} ./micro-services/rooms-service
+          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/notifications-service:${VERSION} ./micro-services/notifications-service
+          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/front-app:${VERSION} ./front
+          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/prometheus-service:${VERSION} ./monitoring/prometheus
 
-          docker push ${{ secrets.DOCKERHUB_USERNAME }}/users-service:$VERSION
-          docker push ${{ secrets.DOCKERHUB_USERNAME }}/movies-service:$VERSION
-          docker push ${{ secrets.DOCKERHUB_USERNAME }}/search-service:$VERSION
-          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sessions-service:$VERSION
-          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rooms-service:$VERSION
-          docker push ${{ secrets.DOCKERHUB_USERNAME }}/notifications-service:$VERSION
-          docker push ${{ secrets.DOCKERHUB_USERNAME }}/front-app:$VERSION
-          docker push ${{ secrets.DOCKERHUB_USERNAME }}/prometheus-service:$VERSION
+          docker push ${{ secrets.DOCKERHUB_USERNAME }}/users-service:${VERSION}
+          docker push ${{ secrets.DOCKERHUB_USERNAME }}/movies-service:${VERSION}
+          docker push ${{ secrets.DOCKERHUB_USERNAME }}/search-service:${VERSION}
+          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sessions-service:${VERSION}
+          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rooms-service:${VERSION}
+          docker push ${{ secrets.DOCKERHUB_USERNAME }}/notifications-service:${VERSION}
+          docker push ${{ secrets.DOCKERHUB_USERNAME }}/front-app:${VERSION}
+          docker push ${{ secrets.DOCKERHUB_USERNAME }}/prometheus-service:${VERSION}
 
-          # Save images with the version tag
-          mkdir -p ~/devops/simplo-cine/version
-          for service in movies-service notifications-service rooms-service search-service sessions-service users-service front prometheus; do
-          # Check if the image exists before trying to save
-            if sudo docker images -q "${service}:${VERSION}"; then
-              sudo docker save -o "./devops/simplo-cine/version/${service}_${VERSION}.tar" "${service}:${VERSION}"
-            else
-              echo "Image ${service}:${VERSION} does not exist, skipping save."
-              # Optionnel : Ajoutez un log pour vérifier si l'image existe sans le tag de version
-              if sudo docker images -q "${service}:latest"; then
-                echo "Image ${service}:latest exists, consider using it instead."
-              fi
-            fi
-          done
+          # # Save images with the version tag
+          # mkdir -p ~/devops/simplo-cine/version
+          # for service in movies-service notifications-service rooms-service search-service sessions-service users-service front prometheus; do
+          # # Check if the image exists before trying to save
+          #   if sudo docker images -q "${service}:${VERSION}"; then
+          #     sudo docker save -o "./devops/simplo-cine/version/${service}_${VERSION}.tar" "${service}:${VERSION}"
+          #   else
+          #     echo "Image ${service}:${VERSION} does not exist, skipping save."
+          #     # Optionnel : Ajoutez un log pour vérifier si l'image existe sans le tag de version
+          #     if sudo docker images -q "${service}:latest"; then
+          #       echo "Image ${service}:latest exists, consider using it instead."
+          #     fi
+          #   fi
+          # done
 
-          # Change ownership of tar files to ensure permission
-          sudo chown -R adminlocal:adminlocal ~/devops/simplo-cine/version
+          # # Change ownership of tar files to ensure permission
+          # sudo chown -R adminlocal:adminlocal ~/devops/simplo-cine/version
 
-          # Commit and push the .tar files
-          cd ~/devops/simplo-cine/version
-          if [ "$(ls *.tar 2>/dev/null)" ]; then
-            git add .
-            git commit -m "Add Docker images version ${VERSION}" || echo "No changes to commit."
-            git push origin develop || echo "Failed to push changes."
-          else
-            echo "No .tar files to commit."
-          fi
+          # # Commit and push the .tar files
+          # cd ~/devops/simplo-cine/version
+          # if [ "$(ls *.tar 2>/dev/null)" ]; then
+          #   git add .
+          #   git commit -m "Add Docker images version ${VERSION}" || echo "No changes to commit."
+          #   git push origin develop || echo "Failed to push changes."
+          # else
+          #   echo "No .tar files to commit."
+          # fi
 
       - name: Build and push Nginx image
         run: |
