fix

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -103,30 +103,30 @@ jobs:
           # Créer le répertoire version s'il n'existe pas
           mkdir -p ./version
 
-          # Changer de répertoire
-          cd ./version
+          # # Changer de répertoire
+          # cd ./version
 
-          # Sauvegarder les images Docker avec la version taggée
-          for service in movies-service notifications-service rooms-service search-service sessions-service users-service front; do
-            if sudo docker images -q "${service}:${VERSION}"; then
-              sudo docker save -o "./version/${service}_${VERSION}.tar" "${service}:${VERSION}"
-            else
-              echo "Image ${service}:${VERSION} does not exist, skipping save."
-            fi
-          done
+          # # Sauvegarder les images Docker avec la version taggée
+          # for service in movies-service notifications-service rooms-service search-service sessions-service users-service front; do
+          #   if sudo docker images -q "${service}:${VERSION}"; then
+          #     sudo docker save -o "./version/${service}_${VERSION}.tar" "${service}:${VERSION}"
+          #   else
+          #     echo "Image ${service}:${VERSION} does not exist, skipping save."
+          #   fi
+          # done
 
-          # # Change ownership of tar files to ensure permission
-          # sudo chown -R adminlocal:adminlocal ~/devops/simplo-cine/version
+          # # # Change ownership of tar files to ensure permission
+          # # sudo chown -R adminlocal:adminlocal ~/devops/simplo-cine/version
 
-          # # Commit and push the .tar files
-          # cd ~/devops/simplo-cine/version
-          # if [ "$(ls *.tar 2>/dev/null)" ]; then
-          #   git add .
-          #   git commit -m "Add Docker images version ${VERSION}" || echo "No changes to commit."
-          #   git push origin develop || echo "Failed to push changes."
-          # else
-          #   echo "No .tar files to commit."
-          # fi
+          # # # Commit and push the .tar files
+          # # cd ~/devops/simplo-cine/version
+          # # if [ "$(ls *.tar 2>/dev/null)" ]; then
+          # #   git add .
+          # #   git commit -m "Add Docker images version ${VERSION}" || echo "No changes to commit."
+          # #   git push origin develop || echo "Failed to push changes."
+          # # else
+          # #   echo "No .tar files to commit."
+          # # fi
 
       - name: Build and push Nginx image
         run: |
